[general]
import = ["~/.config/alacritty/catppuccin-mocha.toml"]

[env]
TERM = "xterm-256color"

# [window]
# padding.x = 15
# padding.y = 15
# dynamic_padding = true
# decorations = "buttonless"
# opacity = 0.95
# blur = true
# option_as_alt = "Both"
# startup_mode = "Windowed"
# dynamic_title = true

[font]
normal.family = "MesloLGS Nerd Font Mono"
normal.style = "Regular"
bold.family = "MesloLGS Nerd Font Mono"
bold.style = "Bold"
italic.family = "MesloLGS Nerd Font Mono"
italic.style = "Italic"
bold_italic.family = "MesloLGS Nerd Font Mono"
bold_italic.style = "Bold Italic"
size = 13.0
offset.x = 0
offset.y = 1
glyph_offset.x = 0
glyph_offset.y = 0
builtin_box_drawing = true

[scrolling]
history = 100000
multiplier = 3

# [cursor]
# style.shape = "Block"
# style.blinking = "On"
# vi_mode_style.shape = "Beam"
# vi_mode_style.blinking = "On"
# blink_interval = 750
# blink_timeout = 5
# unfocused_hollow = true
# thickness = 0.15

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[mouse]
hide_when_typing = true
bindings = [
  { mouse = "Middle", action = "PasteSelection" },
  { mouse = "Right", action = "Paste" },
]


[keyboard]
bindings = [
  { key = "V", mods = "Command", action = "Paste" },
  { key = "C", mods = "Command", action = "Copy" },
  { key = "Q", mods = "Command", action = "Quit" },
  { key = "W", mods = "Command", action = "Quit" },
  { key = "N", mods = "Command", action = "CreateNewWindow" },
  { key = "Return", mods = "Command", action = "ToggleFullscreen" },
  { key = "Plus", mods = "Command", action = "IncreaseFontSize" },
  { key = "Minus", mods = "Command", action = "DecreaseFontSize" },
  { key = "Key0", mods = "Command", action = "ResetFontSize" },
  { key = "K", mods = "Command", action = "ClearHistory" },
  { key = "K", mods = "Command|Shift", action = "ClearHistory" },
  { key = "L", mods = "Control", action = "ClearLogNotice" },
  { key = "L", mods = "Control", chars = "\u000c" },
  { key = "PageUp", mods = "Shift", mode = "~Alt", action = "ScrollPageUp" },
  { key = "PageDown", mods = "Shift", mode = "~Alt", action = "ScrollPageDown" },
  { key = "Home", mods = "Shift", mode = "~Alt", action = "ScrollToTop" },
  { key = "End", mods = "Shift", mode = "~Alt", action = "ScrollToBottom" },
  { key = "Space", mods = "Shift|Control", mode = "~Search", action = "ToggleViMode" },
  { key = "Space", mods = "Shift|Control", mode = "Vi|~Search", action = "ScrollToBottom" },
  { key = "Escape", mode = "Vi|~Search", action = "ClearSelection" },
  { key = "Y", mode = "Vi|~Search", action = "Copy" },
  { key = "Y", mode = "Vi|~Search", action = "ClearSelection" },
  { key = "H", mode = "Vi|~Search", action = "ScrollToTop" },
  # { key = "M", mode = "Vi|~Search", action = "ScrollToCenter" },
  { key = "L", mode = "Vi|~Search", action = "ScrollToBottom" },
]

[bell]
animation = "EaseOutExpo"
duration = 100
color = "#ffffff"
command = "None"
